---
- name: Deploy Application into eks cluster 
  hosts: localhost
  connection: local
  gather_facts: no  # No need to gather facts for this playbook
  become: yes 
  tasks:
    - name: Copy k8s_deployment.yaml file to eks cluster
      copy:
        src: {{ lookup('env','GITHUB_WORKSPACE') }}/Ansible/k8s_deployment.yaml 
        dest: /home/ec2-user/

    - name: Apply Deployment
      ansible.builtin.command: kubectl apply -f /home/ec2-user/k8s_deployment.yaml
    
