# ---
# - name: Deploy Application into eks cluster 
#   hosts: localhost
#   connection: local
#   gather_facts: no  # No need to gather facts for this playbook
#   become: yes 
#   tasks:

#     - name: Apply Deployment
#       ansible.builtin.command: kubectl apply -f /home/runner/work/Ansible_k8s_gha/Ansible_k8s_gha/Ansible/k8s_deployment.yaml
    
- name: Apply Deployment using Ansible k8s module
  community.kubernetes.k8s:
    kubeconfig: /home/runner/.kube/config
    state: present
    src: "{{ playbook_dir }}/k8s_deployment.yaml"
